WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=33249): Read timed out. (read timeout=120)")': /session/1079ad5985326966305693e8ec524909/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=33249): Read timed out. (read timeout=120)")': /session/1079ad5985326966305693e8ec524909/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=33249): Read timed out. (read timeout=120)")': /session/1079ad5985326966305693e8ec524909/screenshot