WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=37377): Read timed out. (read timeout=120)")': /session/0d812987b09f8e64c8b74c5b71beae01/screenshot